export const SCALES = {
  space: ['4px', '8px', '12px', '16px', '20px', '24px', '32px', '40px', '48px', '64px'],
  radius: {
    none: '0px',
    xs: '2px',
    sm: '4px',
    md: '6px',
    lg: '8px',
    xl: '12px',
    '2xl': '16px',
    full: '9999px',
  },
  control: { sm: '32px', md: '36px', lg: '40px' },
} as const;

export const SEMANTIC_VARS = [
  'background',
  'surface',
  'surface-raised',
  'surface-subtle',
  'surface-muted',
  'surface-hover',
  'foreground',
  'foreground-secondary',
  'foreground-muted',
  'foreground-disabled',
  'surface-disabled',
  'border-subtle',
  'border',
  'border-strong',
  'border-interactive',
  'brand',
  'action',
  'action-hover',
  'action-pressed',
  'action-foreground',
  'accent',
  'accent-hover',
  'selection',
  'focus',
  'scrim',
  'shadow-floating',
  'success',
  'success-surface',
  'success-foreground',
  'warning',
  'warning-surface',
  'warning-foreground',
  'danger',
  'danger-hover',
  'danger-surface',
  'danger-foreground',
  'info',
  'info-surface',
  'info-foreground',
  'running',
  'running-surface',
  'running-foreground',
] as const;

export type ThemeVar = (typeof SEMANTIC_VARS)[number];
