import * as React from 'react';
import { useTranslation } from 'react-i18next';

export function UsagePage() {
  const { t } = useTranslation();
  const [interval, setInterval] = React.useState('30d');
  const [includeLocal, setIncludeLocal] = React.useState(true);

  const metrics = [
    { label: 'Total Invocations', value: '42', detail: 'Local agent loops' },
    { label: 'Prompt Tokens', value: '84,210', detail: 'Zero cloud egress' },
    { label: 'Completion Tokens', value: '29,400', detail: 'Ollama local engine' },
    { label: 'External Cloud Spend', value: '$0.00', detail: '100% on-device' },
  ];

  const recentModels = [
    { model: 'qwen2.5-coder:7b', provider: 'Ollama (Local)', calls: 36, percentage: '85%' },
    { model: 'llama3.2:3b', provider: 'Ollama (Local)', calls: 6, percentage: '15%' },
  ];

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div>
        <h2 className="text-xl font-bold tracking-tight text-foreground">
          {t('settings.usage.title', { defaultValue: 'Usage & Analytics' })}
        </h2>
        <p className="text-xs text-foreground-secondary mt-1">
          {t('settings.usage.desc', {
            defaultValue:
              'Local resource consumption metrics, token counts, and invocation breakdowns.',
          })}
        </p>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4 py-2 border-b border-border-subtle pb-4">
        {metrics.map((m) => (
          <div key={m.label} className="space-y-1">
            <span className="text-xs text-foreground-secondary">{m.label}</span>
            <div className="text-xl font-bold text-foreground font-mono">{m.value}</div>
            <div className="text-xs text-success font-medium">{m.detail}</div>
          </div>
        ))}
      </div>

      {/* Analytics Preferences Section */}
      <section aria-labelledby="analytics-options-heading" className="space-y-4">
        <div className="border-b border-border-subtle pb-2.5">
          <h3 id="analytics-options-heading" className="text-sm font-semibold text-foreground">
            Analytics options
          </h3>
        </div>
        <div className="space-y-4">
          {/* Timeframe */}
          <div className="flex items-center justify-between">
            <div>
              <div className="text-sm font-medium text-foreground">Reporting timeframe</div>
              <div className="text-xs text-foreground-secondary mt-0.5">
                Calculate aggregated tokens and invocation count within window
              </div>
            </div>
            <select
              value={interval}
              onChange={(e) => setInterval(e.target.value)}
              className="min-h-control-sm rounded-md border border-border-subtle bg-surface px-3 py-1 text-xs text-foreground cursor-pointer hover:bg-surface-hover focus-visible:outline-2 focus-visible:outline-focus"
            >
              <option value="today">Today</option>
              <option value="7d">Last 7 days</option>
              <option value="30d">Last 30 days</option>
              <option value="month">This calendar month</option>
            </select>
          </div>

          {/* Include local tokens */}
          <div className="flex items-center justify-between">
            <div>
              <div className="text-sm font-medium text-foreground">Track local model tokens</div>
              <div className="text-xs text-foreground-secondary mt-0.5">
                Record execution token counts generated by on-device Ollama instances
              </div>
            </div>
            <button
              type="button"
              role="switch"
              aria-checked={includeLocal}
              aria-label="Track local model tokens"
              onClick={() => setIncludeLocal(!includeLocal)}
              className={`relative inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full px-0.5 transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus ${
                includeLocal ? 'bg-action' : 'bg-surface-muted'
              }`}
            >
              <span
                className={`pointer-events-none inline-block size-4 transform rounded-full bg-surface shadow-sm transition-transform ${
                  includeLocal ? 'translate-x-4' : 'translate-x-0'
                }`}
              />
            </button>
          </div>
        </div>
      </section>

      {/* Model Utilization Section */}
      <section aria-labelledby="model-utilization-heading" className="space-y-4">
        <div className="border-b border-border-subtle pb-2.5">
          <h3 id="model-utilization-heading" className="text-sm font-semibold text-foreground">
            Model utilization
          </h3>
        </div>
        <div className="space-y-4">
          {recentModels.map((row) => (
            <div key={row.model} className="flex items-center justify-between">
              <div>
                <span className="text-sm font-medium text-foreground">{row.model}</span>
                <span className="ms-2 text-xs text-foreground-secondary">({row.provider})</span>
              </div>
              <div className="flex items-center gap-3">
                <span className="font-mono text-xs text-foreground-secondary">
                  {row.calls} calls
                </span>
                <span className="rounded bg-selection px-2 py-0.5 text-xs font-medium text-action">
                  {row.percentage}
                </span>
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
