// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationId } from "./InstallationId";
import type { ProjectId } from "./ProjectId";
import type { SessionId } from "./SessionId";
import type { WorkspaceId } from "./WorkspaceId";

export type EventScope = { installation_id: InstallationId, workspace_id: WorkspaceId | null, project_id: ProjectId | null, session_id: SessionId | null, };
