// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicErrorCode = "InvalidProtocolVersion" | "InvalidRequest" | "PayloadTooLarge" | "RateLimited" | "WorkspaceNotFound" | "ProjectNotFound" | "SessionNotFound" | "ContextMismatch" | "RequestIdConflict" | "ConcurrencyConflict" | "StorageStarting" | "StorageUnavailable" | "StorageRepairRequired" | "ProjectionUnavailable" | "CommandTimedOut" | "InternalError";
