// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandResult<T> = { protocolVersion: number, requestId: string, correlationId: string, data: T, };
