// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandContext } from "./CommandContext";

export type CommandEnvelope<T> = { protocolVersion: number, requestId: string, context: CommandContext, payload: T, };
