// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConversationMessageDto = { messageId: string, role: string, text: string, createdAt: string, sourceEventId: string, };
