// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubmittedMessage = { messageId: string, sessionId: string, text: string, createdAt: string, streamSequence: string, projectionPosition: string, };
