use adham_core_types::{ActorKind, EventActor, EventScope};
use adham_desktop_api::{
    BootstrapState, CommandContext, ConversationMessageDto, ConversationPage, CreateProjectPayload,
    CreateSessionPayload, CreateWorkspacePayload, ProjectSummary, RebuildProjectionsResponse,
    SessionSummary, StorageStatus, SubmitMessagePayload, SubmittedMessage, WorkspaceSummary,
};
use std::fs;
use std::path::Path;
use ts_rs::TS;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = std::env::args().skip(1);
    match args.next().as_deref() {
        Some("contracts") => generate_contracts()?,
        Some(cmd) => {
            eprintln!("Unknown xtask command: {cmd}");
            std::process::exit(1);
        }
        None => {
            println!("Usage: cargo xtask <contracts>");
        }
    }
    Ok(())
}

fn generate_contracts() -> Result<(), Box<dyn std::error::Error>> {
    println!("Generating TypeScript contracts into packages/contracts-generated/src/index.ts...");

    let mut content = String::new();
    content.push_str("// Auto-generated by `cargo xtask contracts`. DO NOT EDIT MANUALLY.\n\n");

    content.push_str("export interface CommandEnvelope<T> {\n");
    content.push_str("  protocolVersion: number;\n");
    content.push_str("  requestId: string;\n");
    content.push_str("  context: CommandContext;\n");
    content.push_str("  payload: T;\n");
    content.push_str("}\n\n");

    content.push_str("export interface CommandResult<T> {\n");
    content.push_str("  protocolVersion: number;\n");
    content.push_str("  requestId: string;\n");
    content.push_str("  correlationId: string;\n");
    content.push_str("  data: T;\n");
    content.push_str("}\n\n");

    let decls = [
        ActorKind::decl(),
        EventActor::decl(),
        EventScope::decl(),
        CommandContext::decl(),
        BootstrapState::decl(),
        CreateWorkspacePayload::decl(),
        WorkspaceSummary::decl(),
        CreateProjectPayload::decl(),
        ProjectSummary::decl(),
        CreateSessionPayload::decl(),
        SessionSummary::decl(),
        SubmitMessagePayload::decl(),
        SubmittedMessage::decl(),
        ConversationMessageDto::decl(),
        ConversationPage::decl(),
        StorageStatus::decl(),
        RebuildProjectionsResponse::decl(),
    ];

    let id_types = [
        "export type InstallationId = string;",
        "export type WorkspaceId = string;",
        "export type ProjectId = string;",
        "export type SessionId = string;",
        "export type MessageId = string;",
        "export type RequestId = string;",
        "export type CorrelationId = string;",
        "export type ContentId = string;",
        "export type EventId = string;",
        "export type ActorId = string;",
    ];

    for id_decl in id_types {
        content.push_str(id_decl);
        content.push_str("\n");
    }
    content.push_str("\n");

    for decl in decls {
        if !decl.starts_with("export") {
            content.push_str("export ");
        }
        content.push_str(&decl);
        content.push_str("\n\n");
    }

    let target_path = Path::new("packages/contracts-generated/src/index.ts");
    if let Some(parent) = target_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(target_path, content)?;

    println!("TypeScript contracts generated successfully.");
    Ok(())
}
