// Auto-generated by `cargo xtask contracts`. DO NOT EDIT MANUALLY.

export interface CommandEnvelope<T> {
  protocolVersion: number;
  requestId: string;
  context: CommandContext;
  payload: T;
}

export interface CommandResult<T> {
  protocolVersion: number;
  requestId: string;
  correlationId: string;
  data: T;
}

export type InstallationId = string;
export type WorkspaceId = string;
export type ProjectId = string;
export type SessionId = string;
export type MessageId = string;
export type RequestId = string;
export type CorrelationId = string;
export type ContentId = string;
export type EventId = string;
export type ActorId = string;

export type ActorKind = "LocalHuman" | "System" | "Migration";

export type EventActor = { actor_id: ActorId, kind: ActorKind, };

export type EventScope = { installation_id: InstallationId, workspace_id: WorkspaceId | null, project_id: ProjectId | null, session_id: SessionId | null, };

export type CommandContext = { workspaceId: string | null, projectId: string | null, sessionId: string | null, };

export type BootstrapState = { isInitialized: boolean, activeWorkspaceId: string | null, activeProjectId: string | null, };

export type CreateWorkspacePayload = { name: string, kind: string, preferredLanguage: string, };

export type WorkspaceSummary = { workspaceId: string, name: string, kind: string, preferredLanguage: string, createdAt: string, };

export type CreateProjectPayload = { name: string, storageKind: string, };

export type ProjectSummary = { projectId: string, workspaceId: string, name: string, storageKind: string, createdAt: string, };

export type SelectProjectPayload = { projectId: string, };

export type CreateSessionPayload = { title: string | null, };

export type SessionSummary = { sessionId: string, projectId: string, title: string | null, createdAt: string, };

export type SubmitMessagePayload = { text: string, };

export type SubmittedMessage = { messageId: string, sessionId: string, text: string, createdAt: string, streamSequence: string, projectionPosition: string, };

export type ConversationMessageDto = { messageId: string, role: string, text: string, createdAt: string, sourceEventId: string, };

export type ConversationPage = { items: Array<ConversationMessageDto>, nextCursor: string | null, projectionPosition: string, };

export type StorageStatus = { status: string, journalMode: string, schemaVersion: number, };

export type RebuildProjectionsResponse = { replayedCount: bigint, };

